bot_token = ""
application_id = ""
guild_id = ""

[log]
path = "bot.json.log"
colorize = true
verify_channel = ""
submissions_channel = ""

[api]
url = "https://api.turkb.us/v2"
token = ""

[submission]
questions = []
role = ""
